# Generated by Django 5.2.12 on 2026-03-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When supplier confirmed receipt via email link', null=True),
        ),
    ]
