# Generated by Django 5.2.12 on 2026-03-28 07:35

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('grade', models.CharField(blank=True, help_text='e.g. Grade 60, S275, C25/30, F17', max_length=100)),
                ('standard', models.CharField(blank=True, help_text='e.g. ASTM A615, BS 4449, NSCP 2015', max_length=100)),
                ('certification', models.CharField(blank=True, help_text='e.g. ISO 9001, PNS certified, mill cert required', max_length=200)),
                ('compressive_strength', models.CharField(blank=True, help_text='e.g. 3000 psi, 20 MPa', max_length=50)),
                ('yield_strength', models.CharField(blank=True, help_text='e.g. 60,000 psi, 415 MPa', max_length=50)),
                ('mix_ratio', models.CharField(blank=True, help_text='e.g. 1:2:4, 1:1.5:3 (cement:sand:gravel)', max_length=100)),
                ('diameter', models.DecimalField(blank=True, decimal_places=3, help_text='mm', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, help_text='mm or m depending on item', max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, help_text='mm', max_digits=10, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, help_text='mm', max_digits=10, null=True)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=4, help_text='kg per piece/unit', max_digits=10, null=True)),
                ('material_type', models.CharField(blank=True, help_text='e.g. deformed bar, plain bar, OPC, PPC, softwood, hardwood', max_length=100)),
                ('finish', models.CharField(blank=True, help_text='e.g. galvanized, painted, rough-sawn, dressed', max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any additional technical notes or special handling instructions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('client', models.CharField(blank=True, max_length=200)),
                ('location', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='unit_type',
            field=models.CharField(choices=[('WEIGHT', 'Weight'), ('VOLUME', 'Volume'), ('LENGTH', 'Length'), ('AREA', 'Area'), ('COUNT', 'Count'), ('OTHER', 'Other')], default='COUNT', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='material_spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='inventory.materialspec'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('transaction_type', models.CharField(choices=[('MANUAL_IN', 'Manual Stock In'), ('INITIAL_STOCK', 'Initial Stock'), ('PO_RECEIPT', 'Purchase Order Receipt'), ('DO_DISPATCH', 'Delivery Order Dispatch'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Return to Stock'), ('PROJECT_ISSUE', 'Issued to Project')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=4, help_text='Positive = stock in, Negative = stock out', max_digits=12)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reason_note', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.item')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project this transaction is tied to, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.project')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allocated_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('delivered_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('PARTIAL', 'Partially Delivered'), ('DELIVERED', 'Fully Delivered'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('display_uom', models.ForeignKey(blank=True, help_text='UOM to display quantities in for this project (can differ from item UOM)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unitofmeasure')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_allocations', to='inventory.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('factor', models.DecimalField(decimal_places=10, help_text='Multiply from_unit quantity by this to get to_unit quantity.', max_digits=20)),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.unitofmeasure')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='inventory.unitofmeasure')),
            ],
            options={
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
